# .github/release.yaml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 💥 Breaking Change
      labels:
        - breaking-change
    - title: 🚀 Enhancement
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fix
      labels:
        - bug
    - title: 📝 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
