import { getTokenType } from "./getTokenType.js"
import { jwtDecode } from "./jwtDecode.js"

describe("getTokenType", () => {
  it('should be able to parse a "dashboard" access token.', () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJleW9aT0Z2UFdXIiwic2x1ZyI6ImRlbW8tc3RvcmUiLCJlbnRlcnByaXNlIjp0cnVlLCJyZWdpb24iOiJldS13ZXN0LTEifSwiYXBwbGljYXRpb24iOnsiaWQiOiJvR0xQWGliV1JlIiwiY2xpZW50X2lkIjoiOHUtQ29tYkJRRGJtaGxPMEtkMWFmQjBCWVFYTi04Yy1zRnBWVmd1NHZ5VSIsImtpbmQiOiJkYXNoYm9hcmQiLCJwdWJsaWMiOmZhbHNlLCJjb25maWRlbnRpYWwiOnRydWV9LCJvd25lciI6eyJpZCI6ImVEd0tTT1h5RXEiLCJ0eXBlIjoiVXNlciJ9LCJzY29wZSI6Im1hcmtldDphbGwiLCJleHAiOjE3NzE1MzY2MDUsInRlc3QiOnRydWUsInJhbmQiOjAuMTk4NzQ4NjQ4MTA4OTgzNzQsImlhdCI6MTc3MTUyOTQwNSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmNvbW1lcmNlbGF5ZXIuaW8ifQ.ZeN9fN_tEZraBC-PjA4SHh5VzwVoQP1Ask5FSkpWY5T-MnLTprolVCB7oXDFHw0HROEDoscdsU_sEFWDp13URepQZ5T0WAcHMu7RS0BYn0VVpE6KTdahmzKNgTlK-5_4D7NzFTiH7oz97KCVRSfDHuO7HXXz7eQHsMxNdSQnfU6lbQYFG52ubmRmcl-Q6R3b9TUWh8tmAqmB6hQiMaR19G0x-xWxysHrUOu1Zq6k0onmPIEv5wE64rDQnh-c4Qx22YIcbWYLhpc5tYWOlp1H8gPuZGcfGF_dIP1LiQSBQefCWeK_3BXwLG67D-I4n3iwmO8ROiziYqogmIr4zA3olA"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("dashboard:user")
  })

  it('should be able to parse a "provisioning" access token (`client_credentials` grant type).', () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImFiYTRjYzYyOGQxZmNlM2ZiOTNhM2VlNTU4MjZlNDFjZmFmMThkYzJkZmYzYjA3MjIyNzQwMzgwZTkxOTlkNWQifQ.eyJ1c2VyIjp7ImlkIjoiZ2Jsb3dTeVZlcSJ9LCJhcHBsaWNhdGlvbiI6eyJpZCI6Im5HVnFhaWxWeU4iLCJraW5kIjoidXNlciIsInB1YmxpYyI6ZmFsc2V9LCJzY29wZSI6InByb3Zpc2lvbmluZy1hcGkiLCJleHAiOjE3MTA5NTA0MzAsInRlc3QiOmZhbHNlLCJyYW5kIjowLjY2OTAzODQ1MzY1NjE5MzMsImlhdCI6MTcxMDk0MzIzMCwiaXNzIjoiaHR0cHM6Ly9jb21tZXJjZWxheWVyLmlvIn0.NB1PVDXU-CbatAkOKUyKDVo4e1YrracajM1JXUZCnDqGPyD2oMzCQC9ztqtOXrbvlV3FHIWm0yzd8yQvKokFjvPDDH9TvfuWgi_hFN-Dh_7IZBj0tUBfUmF694QfrUOoRfX5OX-jBkRk0IrlYUi2WleiilkSbTV9YdAiLNDWFA1MjeK7YS-QLzrrYL6RsUcII4qrDb7UZZOWiZiXTbZ1HFiSZacrZfu3Eu1BGKVUl8ZhhgYOJ1mCPlVmqn4OTnMfZby8M8Jvo3z7HDbC1-lCWMhoQ7o_PH-duA4DnaMyVrchw1S_3aSmVx6rWykvZ80d9Qz-8oSvqZwhkmnMFvUKvQ"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("user:guest")
  })

  it('should be able to parse a "sales_channel" access token (`client_credentials` grant type).', () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImFiYTRjYzYyOGQxZmNlM2ZiOTNhM2VlNTU4MjZlNDFjZmFmMThkYzJkZmYzYjA3MjIyNzQwMzgwZTkxOTlkNWQifQ.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJlbldveEZNT25wIiwic2x1ZyI6InRoZS1ibHVlLWJyYW5kLTMiLCJlbnRlcnByaXNlIjpmYWxzZSwicmVnaW9uIjoiZXUtd2VzdC0xIn0sImFwcGxpY2F0aW9uIjp7ImlkIjoibkdWcWFpRVlOQSIsImtpbmQiOiJzYWxlc19jaGFubmVsIiwicHVibGljIjp0cnVlfSwic2NvcGUiOiJtYXJrZXQ6YWxsIiwiZXhwIjoxNzEwOTU3NjMwLCJ0ZXN0Ijp0cnVlLCJyYW5kIjowLjM0Nzg4MjA0NDE1NDI0Njk1LCJpYXQiOjE3MTA5NDMyMzAsImlzcyI6Imh0dHBzOi8vY29tbWVyY2VsYXllci5pbyJ9.XhcMqwVwAh5wP2rbNyODBuPpTicwJjvK09KPmhe3nM1Lg0Hp0bIEQIOS81ohLyLE9ecaRH_7CsfLkAqYmRtdOTAKu9m4xvWw-Z_hBQpY67FTaikInMVltNffLvNDe5qmleNi5jnXtJl_yEGhtlDydpFBx1x8u3ofgtZSPFWm3Tl4KQoxFxT8CnnxPd2LTW_PfvnqS3QEGgvVnEXSTnJ41EU4dB8c9cZmmJY6e9SeH9fHVd469N_ipP4bymIL7kLPpkBBDuxxZ0787dOblGI31geAW-hHGbCpnj4_i5WJAVVsj_ImBtqt9Bihc-O-iHIMJlVOzWWXTAnmWGsHiwL5Ag"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("sales_channel:guest")
  })

  it('should be able to parse an "integration" access token (`client_credentials` grant type).', () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImFiYTRjYzYyOGQxZmNlM2ZiOTNhM2VlNTU4MjZlNDFjZmFmMThkYzJkZmYzYjA3MjIyNzQwMzgwZTkxOTlkNWQifQ.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJlbldveEZNT25wIiwic2x1ZyI6InRoZS1ibHVlLWJyYW5kLTMiLCJlbnRlcnByaXNlIjpmYWxzZSwicmVnaW9uIjoiZXUtd2VzdC0xIn0sImFwcGxpY2F0aW9uIjp7ImlkIjoiZE1uV21pZ2FwYiIsImtpbmQiOiJpbnRlZ3JhdGlvbiIsInB1YmxpYyI6ZmFsc2V9LCJzY29wZSI6Im1hcmtldDphbGwiLCJleHAiOjE3MTA5NTA0MzAsInRlc3QiOnRydWUsInJhbmQiOjAuMjE0Njc5MzMzMDQ0NTc2NzYsImlhdCI6MTcxMDk0MzIzMCwiaXNzIjoiaHR0cHM6Ly9jb21tZXJjZWxheWVyLmlvIn0.dkTswP2_lUwsKDoR8ogdCeGHgoY2zsVAl3kvX8nVBnQJh5N7ODCBGa3Rjy0MkUna7ufiAjUbuSAW8Crm8Jli3eh1WPq3nEkzjnlz8N9syRBgdKwkS46Z-3ZCEdRTBikkF38GAQIDhCqZ6ar6hIdm-6FRxDxSCzQ0zcruJc9g8EwXAO4BhvPOAw3gZ6O2uiLlQSxH3dAqg0qWehMhtZODMtFngBh38pOWbO3tRk1ojyfUq1Ckow8NyVPQa38suIf1wlrKkyKS3okP1WsN2ux7kVn8cXZ3uaP9rsKM82wICYgXfmlcxA-6AlKfgZ5ExCsCOVfubwSy8tUAGp_EPGDr9w"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("integration:guest")
  })

  it('should be able to parse a "customer" access token (`password` grant type).', () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImFiYTRjYzYyOGQxZmNlM2ZiOTNhM2VlNTU4MjZlNDFjZmFmMThkYzJkZmYzYjA3MjIyNzQwMzgwZTkxOTlkNWQifQ.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJlbldveEZNT25wIiwic2x1ZyI6InRoZS1ibHVlLWJyYW5kLTMiLCJlbnRlcnByaXNlIjpmYWxzZSwicmVnaW9uIjoiZXUtd2VzdC0xIn0sImFwcGxpY2F0aW9uIjp7ImlkIjoibkdWcWFpRVlOQSIsImtpbmQiOiJzYWxlc19jaGFubmVsIiwicHVibGljIjp0cnVlfSwibWFya2V0Ijp7ImlkIjpbIkJqeHJKaHltbE0iXSwic3RvY2tfbG9jYXRpb25faWRzIjpbInhHWEJYdXJETUUiLCJkTXFYeXVWVmtOIl0sImdlb2NvZGVyX2lkIjpudWxsLCJhbGxvd3NfZXh0ZXJuYWxfcHJpY2VzIjpmYWxzZX0sIm93bmVyIjp7ImlkIjoiZ09xelpoWnJtUSIsInR5cGUiOiJDdXN0b21lciJ9LCJzY29wZSI6Im1hcmtldDo1OCIsImV4cCI6MTcxMDk1NzYzMCwidGVzdCI6dHJ1ZSwicmFuZCI6MC45MzMzMzg0ODA2MzUxODksImlhdCI6MTcxMDk0MzIzMCwiaXNzIjoiaHR0cHM6Ly9jb21tZXJjZWxheWVyLmlvIn0.DC-XTnNf8i-4yWFq3SsVJEuDDIwXnKK6ALWw0vzizYlMb9tRk100TCcgaWiicmC86YuUmS3fsNt2d2rC9f_cE3CxBqwg8ncaSGore59pWBHMH45e6M2DR09K2oFzQk4ZJf3pngqydo_N9Ds6xGZW7vIff9Ga247pAu3-FSahjvhpKXMDkdYB769VGctYOlT1Xz1KCwB0JVpLjr7AR2i8S6R8GAdV3-YNUF_KzYm7qz0jmp7_guqUkYURHSugu9kXMkvUmb6KpyrpW-YBeE789TDra6dXK29WeEtq_nkBZKNmgPOfEEdM2RegmzEFpZNdanbtj__B_i-axqjnJ5lqMQ"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("sales_channel:customer")
  })

  it('should be able to parse a "refreshed customer" access token (`refresh_token` grant type).', () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImFiYTRjYzYyOGQxZmNlM2ZiOTNhM2VlNTU4MjZlNDFjZmFmMThkYzJkZmYzYjA3MjIyNzQwMzgwZTkxOTlkNWQifQ.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJlbldveEZNT25wIiwic2x1ZyI6InRoZS1ibHVlLWJyYW5kLTMiLCJlbnRlcnByaXNlIjpmYWxzZSwicmVnaW9uIjoiZXUtd2VzdC0xIn0sImFwcGxpY2F0aW9uIjp7ImlkIjoibkdWcWFpRVlOQSIsImtpbmQiOiJzYWxlc19jaGFubmVsIiwicHVibGljIjp0cnVlfSwibWFya2V0Ijp7ImlkIjpbIkJqeHJKaHltbE0iXSwic3RvY2tfbG9jYXRpb25faWRzIjpbInhHWEJYdXJETUUiLCJkTXFYeXVWVmtOIl0sImdlb2NvZGVyX2lkIjpudWxsLCJhbGxvd3NfZXh0ZXJuYWxfcHJpY2VzIjpmYWxzZX0sIm93bmVyIjp7ImlkIjoiZ09xelpoWnJtUSIsInR5cGUiOiJDdXN0b21lciJ9LCJzY29wZSI6Im1hcmtldDo1OCIsImV4cCI6MTcxMDk1NzYzMSwidGVzdCI6dHJ1ZSwicmFuZCI6MC40NjI5MTU5OTg3OTQyODk2LCJpYXQiOjE3MTA5NDMyMzEsImlzcyI6Imh0dHBzOi8vY29tbWVyY2VsYXllci5pbyJ9.liTBwOIvx_LeVeBRGm4NwQCOR5F4SDVRVzaHM8uw4oihgUCo-IMktSJs8IRCyUfLfBNhsFfDjwkOXSY7-ApPT5-pMZ-cU3PP9EyFPH5pS9BpMOrhQfQaa9wYhC7r3c4MFwM7NuWRCpgie-juMWxUz1IwX-GfqCe_la6k9qwC8xdMNjfPHohjIEyfqD6TEYd69IxeBBxK_yOZ0zi4yOSo9-6y9T9i5EhMi5MPM8wHR0T9oPD0s-HrC23bMQ2s5asIzrwCRzmu1ZsQp3yf0UVpYuoNstQqUSTHWO5anh0oMipQtOphnczago85TPALDbY8AlaAZTIirXFgNHmCQpX4gQ"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("sales_channel:customer")
  })

  it('should be able to parse a "webapp" access token (`authorization_code` grant type).', () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImFiYTRjYzYyOGQxZmNlM2ZiOTNhM2VlNTU4MjZlNDFjZmFmMThkYzJkZmYzYjA3MjIyNzQwMzgwZTkxOTlkNWQifQ.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJlbldveEZNT25wIiwic2x1ZyI6InRoZS1ibHVlLWJyYW5kLTMiLCJlbnRlcnByaXNlIjpmYWxzZSwicmVnaW9uIjoiZXUtd2VzdC0xIn0sImFwcGxpY2F0aW9uIjp7ImlkIjoiR1J2RGlySmxERyIsImtpbmQiOiJ3ZWJhcHAiLCJwdWJsaWMiOmZhbHNlfSwibWFya2V0Ijp7ImlkIjpbIkJqeHJKaHltbE0iXSwic3RvY2tfbG9jYXRpb25faWRzIjpbInhHWEJYdXJETUUiLCJkTXFYeXVWVmtOIl0sImdlb2NvZGVyX2lkIjpudWxsLCJhbGxvd3NfZXh0ZXJuYWxfcHJpY2VzIjpmYWxzZX0sIm93bmVyIjp7ImlkIjoiZ2Jsb3dTeVZlcSIsInR5cGUiOiJVc2VyIn0sInNjb3BlIjoibWFya2V0OmlkOnJvYkFuaFBkR2wiLCJleHAiOjE3MTA5NzQwMTksInRlc3QiOnRydWUsInJhbmQiOjAuMDYwMTE4MTU0OTMxNDIzOTIsImlhdCI6MTcxMDk2NjgxOSwiaXNzIjoiaHR0cHM6Ly9jb21tZXJjZWxheWVyLmlvIn0.RhXDw7UajFr9Bxl18Q8Es82MlbXw1YcJCRe0g1-mPpDaxcBDtvHyu8GQYLpRYm-4xQ5fbg57Pzqxue0jOxv2Kcsl7XhOUHwEs9jTyS5_tfeJTQ_Ab4zKi27EFfb9NmA78xXEa1wyznVDoYvUy-PzemPPchEDezx1qrJkd0zMqnr5CJntSmfPCP22g0ljLscNUtUlbACT7xpIVXAe37XZ6_DBHOuAToleupFoyUKbNH3fRTc3FIrzexWt1m8RQALQ-QGDPljjFpnWjo3aiJQMZAu9FoZgdJn-qlbW0iYRFl91TAu8VAJ8bJJo8o3jbNdlggs9kNYFy3h15Zx3rnOUyA"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("webapp:user")
  })

  it("should be able to parse an access token with custom claims and special chars.", () => {
    const accessToken =
      "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImFiYTRjYzYyOGQxZmNlM2ZiOTNhM2VlNTU4MjZlNDFjZmFmMThkYzJkZmYzYjA3MjIyNzQwMzgwZTkxOTlkNWQifQ.eyJvcmdhbml6YXRpb24iOnsiaWQiOiJlbldveEZNT25wIiwic2x1ZyI6InRoZS1ibHVlLWJyYW5kLTMiLCJlbnRlcnByaXNlIjpmYWxzZSwicmVnaW9uIjoiZXUtd2VzdC0xIn0sImFwcGxpY2F0aW9uIjp7ImlkIjoiR1J2RGlySmxERyIsImtpbmQiOiJ3ZWJhcHAiLCJwdWJsaWMiOmZhbHNlfSwiY3VzdG9tX2NsYWltIjp7ImN1c3RvbWVyIjp7ImZpcnN0X25hbWUiOiJKw7ZyZyIsImxhc3RfbmFtZSI6IkRvZSJ9fSwic2NvcGUiOiJtYXJrZXQ6YWxsIiwiZXhwIjoxNzI5Nzc5MTQ0LCJ0ZXN0Ijp0cnVlLCJyYW5kIjowLjY5NzY2MjgwNDM2NTg2OTUsImlhdCI6MTcyOTc3MTk0NCwiaXNzIjoiaHR0cHM6Ly9hdXRoLmNvbW1lcmNlbGF5ZXIuY28ifQ.jtOrSfSZMITiiYLqmu5p5oiY3pZnQSGNvDeN7nMQ7vpTByMvy-XQvY9YVCVxCwqDy3I_57c3HiEhgEz47crmv-4g4TpcfFjFqg4i2TQGHf0VNJJ5LOsh_cTUYNf13Q7Vy5jmrJ-sC8MJ0tEcs-f2ACizCJ_uRCqvybB-WwmeIf9A-ExiKN24Ku1Tw9aE0zjuTL3rmwNuR_6H1Umx6XzAQIRjNGL0vOTPTQ52-MrTwV3MYqFxlaWw0HZfr-0RgnUBhXN1LnW4sFYVmLLeYPJ1khYs3blcbKOJo5BQ8Fbnyj7E33Mx2B-3Z63y6uA8vTf45GzucZvIiHBXPeYLtUnglHv9KkhZYksb6xj4WMddZzKGC0r8LVl3ac8ZdWf00epLCBnIDkY8T94NgYF9xCWESB477x8rVLUs8WoKrnvrMzc7OZF2xk22q6Ajc24q9FOhnvymS674N_e1yI5QjNxxZHA5R-W79P-pXbm_nmCRqhKnewZupUKKehbm3SyLYmUndDilJNPkD7qxYZhlDr4rpd5VUpFONAU7qZznGgAak92RY-lJHh-RycyRRf8y-M2Q2jeQfXOrsTXAbK35-c2zvCDXBG7fYTc_fzGZFFMEvMpcfFw4PWfEFZTwxLRWWUHw2WYjg5da94c09z0oUWd2Lmp6P6Yw5vAqeHQn9A5x_y0"

    const { payload } = jwtDecode(accessToken)

    expect(getTokenType(payload)).toBe("webapp:guest")
  })
})
